# Generated by Django 5.1.5 on 2025-03-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='movie/images/')),
                ('area', models.CharField(blank=True, max_length=250)),
                ('date', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
