# Generated by Django 5.1.5 on 2025-04-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_alter_vacante_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='image',
            field=models.ImageField(null=True, upload_to='vacante/images/'),
        ),
    ]
