# Generated by Django 5.1.5 on 2025-04-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0006_alter_vacante_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
